dist: trusty
sudo: required

language: java
jdk:
- oraclejdk8

before_install:
  - mvn clean -q

install:
  - mvn install -DskipTests=true -q
  
before_script:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs librsvg2-dev
  - npm i mathoid
  - cd node_modules/mathoid
  - ./server.js -c config.dev.yaml &
  - cd ../..
